# Generated by Django 6.1 on 2026-08-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_demouser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('technologie', models.CharField(blank=True, max_length=150)),
                ('duree', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('statut', models.CharField(default='Actif', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('duree_mois', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(default='Actif', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(default='Actif', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CursusCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursus_associes', to='api.cours')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_ordre', to='api.cursus')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('cursus', 'cours')},
            },
        ),
        migrations.AddField(
            model_name='cursus',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursus_set', to='api.filiere'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_estimee', models.DateField(blank=True, null=True)),
                ('effectif_max', models.PositiveIntegerField(default=0)),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='api.cursus')),
            ],
        ),
        migrations.CreateModel(
            name='CoursPlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle', models.CharField(blank=True, max_length=150)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('formateur', models.ForeignKey(blank=True, limit_choices_to={'role': 'formateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_planifies', to='api.demouser')),
                ('cursus_cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planifications', to='api.cursuscours')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='api.promotion')),
            ],
            options={
                'unique_together': {('promotion', 'cursus_cours')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='Validée', max_length=30)),
                ('cours_planifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.coursplanifie')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to='api.demouser')),
            ],
            options={
                'unique_together': {('eleve', 'cours_planifie')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='Validée', max_length=30)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_promotion', to='api.demouser')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.promotion')),
            ],
            options={
                'unique_together': {('eleve', 'promotion')},
            },
        ),
    ]
