# Generated by Django 6.1 on 2026-08-20 10:16
"""Crée la table du référentiel des salles (bâtiment, étage, numéro)."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coursplanifie_offres_unitaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_batiment', models.PositiveIntegerField()),
                ('numero_etage', models.PositiveIntegerField()),
                ('numero_salle', models.PositiveIntegerField()),
                ('statut', models.CharField(default='Disponible', max_length=30)),
            ],
            options={
                'ordering': ['numero_batiment', 'numero_etage', 'numero_salle'],
                'unique_together': {('numero_batiment', 'numero_etage', 'numero_salle')},
            },
        ),
    ]
