# Generated by Django 6.1 on 2026-08-20 10:33
"""Retire le statut de Salle et fait du numéro de bâtiment un identifiant textuel (lettres)."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='statut',
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero_batiment',
            field=models.CharField(max_length=10),
        ),
    ]
