// TODO: remplacer par les vraies données du back

export const CURSUS = [
  {
    id: "cda",
    nom: "CDA",
    filiere: "Développement",
    description: "",
    dureeMois: 11,
    nbCours: 24,
    dernModif: "il y a 3 jours",
    statut: "Actif",
    ordrePedagogique: [
      { id: 1, titre: "Algorithmique + Init. Programmation" },
      { id: 2, titre: "Web Client / HTML & CSS" },
      { id: 3, titre: "JavaScript initiation" },
      { id: 4, titre: "Programmation Orientée Objet" },
      { id: 5, titre: "Langage SQL / SQL Server" },
    ],
  },
  {
    id: "tssr",
    nom: "TSSR",
    filiere: "Systèmes et Réseaux",
    description: "",
    dureeMois: 9,
    nbCours: 16,
    dernModif: "il y a 1 semaine",
    statut: "Actif",
    ordrePedagogique: [],
  },
  {
    id: "asr",
    nom: "ASR",
    filiere: "Systèmes et Réseaux",
    description: "",
    dureeMois: 10,
    nbCours: 18,
    dernModif: "il y a 2 semaines",
    statut: "Actif",
    ordrePedagogique: [],
  },
  {
    id: "d2wm",
    nom: "D2WM",
    filiere: "Développement",
    description: "",
    dureeMois: 8,
    nbCours: 14,
    dernModif: "il y a 5 jours",
    statut: "Brouillon",
    ordrePedagogique: [],
  },
  {
    id: "eadl",
    nom: "EADL",
    filiere: "Développement",
    description: "",
    dureeMois: 12,
    nbCours: 20,
    dernModif: "il y a 2 jours",
    statut: "Actif",
    ordrePedagogique: [],
  },
  {
    id: "asd",
    nom: "ASD",
    filiere: "Développement",
    description: "",
    dureeMois: 10,
    nbCours: 18,
    dernModif: "il y a 4 jours",
    statut: "Actif",
    ordrePedagogique: [],
  },
  {
    id: "esd",
    nom: "ESD",
    filiere: "Développement",
    description: "",
    dureeMois: 9,
    nbCours: 16,
    dernModif: "il y a 6 jours",
    statut: "Actif",
    ordrePedagogique: [],
  },
];